---
apiVersion: v1
kind: ConfigMap
metadata:
    name: wp-cm
    labels:
        name: wp-cm
data:
    WORDPRESS_DB_HOST: wpdb-mysql-mysql-master
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_NAME: mydb
