---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wp-pvc
    labels:
        name: wp-pvc
spec:
    storageClassName: do-block-storage
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wp-deploy
    labels:
        name: wp-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            name: wp-pod
    template:
        metadata:
            name: wp-pod
            labels:
                name: wp-pod
        spec:
            volumes:
            - name: wp-vol
              persistentVolumeClaim:
                claimName: wp-pvc
            containers:
            - name: wp-container
              image: wordpress:5
              imagePullPolicy: IfNotPresent
              envFrom:
              - configMapRef:
                    name: wp-cm
              - secretRef:
                    name: wp-secret
              ports:
              - name: wp-port
                containerPort: 80
              volumeMounts:
              - name: wp-vol
                mountPath: /var/www/html

---
apiVersion: v1
kind: Service
metadata:
    name: wp-svc
    labels:
        name: wp-svc
spec:
    type: ClusterIP
    selector:
        name: wp-pod
    ports:
    - port: 80
      targetPort: wp-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: wp-ing
    labels:
        name: wp-ing

spec:
    ingressClassName: nginx
    rules:
    - host: wp.188.166.204.56.nip.io
      http:
            paths:
            - path: /  
              pathType: Prefix
              backend:
                service:
                    name: wp-svc
                    port:
                        number: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: wp-netpol
    labels:
        name: wp-netpol

spec:
    podSelector:
        matchLabels:
            name: wp-pod
    policyTypes:
    - Ingress
    ingress:
    - from:
      - podSelector:
            matchLabels:
                app.kubernetes.io/instance: my-ingress
        namespaceSelector:
            matchLabels:
                name: ingress
      ports:
      - port: wp-port
        protocol: TCP

