---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: bggapp-deploy
    labels:
        name: bggapp-deploy
spec:
    replicas: 2
    selector:
        matchLabels:
            name: bggapp-pod
    template:
        metadata:
            name: bggapp-pod
            labels:
                name: bggapp-pod
        spec:
            containers:
            - name: bggapp-container
              image: chukmunnlee/bggapp:v1
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 3000

              envFrom:
              - configMapRef:
                    name: bgg-cm
              - secretRef:
                    name: bgg-secret

---
apiVersion: v1
kind: Service
metadata:
    name: bggapp-svc
    labels:
        name: bggapp-svc
spec:
    type: ClusterIP
    selector:
        name: bggapp-pod
    ports:
    - port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: bggapp-ing
    labels:
       name: bggapp-ing
spec:
    ingressClassName: nginx
    rules:
    - host: bggapp.188.166.204.56.nip.io
      http:
            paths:
            - path: /  
              pathType: Prefix
              backend:
                service:
                    name: bggapp-svc
                    port:
                        number: 80
