---
apiVersion: v1
kind: ConfigMap
metadata:
    name: bgg-cm
    labels:
        name: bgg-cm
data:
    # fully qualified domain name if using different namespace
    # if same namespace, can just use bggdb-svc
    BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local
    BGG_DB_PORT: "3306"
    BGG_DB_USER: root
