---
# this will create deployment.apps and replicaset.apps
apiVersion: apps/v1
kind: Deployment
metadata:
    name: bggapp-deploy
    labels:
        name: bggdb-deploy
spec:
    replicas: 2
    selector:
        matchLabels:
            name: bggapp-pod
    template:
        metadata:
            name: bggapp-pod
            labels:
                name: bggapp-pod
        spec:
            containers:
            - name: bggapp-container
              image: chukmunnlee/bggapp:v1
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 3000
              envFrom:
              - configMapRef:
                    name: bgg-cm
              - secretRef:
                    name: bgg-secret

---
apiVersion: v1
kind: Service
metadata:
    name: bggapp-svc
    labels:
        name: bggapp-svc

spec:
    type: LoadBalancer
    selector:
        name: bggapp-pod
    ports:
    - port: 80
      targetPort: 3000
